### ISSUE TITLE
KWIVER 1.5 build failure on windows

### ISSUE THREAD

**Issue by aaron-bray** [Kitware/kwiver#1021]
I had to add :
`#include <stdexcept>`
here:
https://github.com/Kitware/kwiver/blob/5a7a959a1df79d1657774b36d2c35be5884850c6/vital/types/track.cxx#L39

to get kwiver 1.5 to compile on windows MSVC 2019 (16.6.2)
due to :
`KWIVER\src\vital\types\track.cxx(138,16): error C2039: 'logic_error': is not a member of 'std'`

Note, I built both the basic KWIVER (no added cmake options) and with ARROWS and PROJ
