### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by skn123** [Kitware/kwiver#54]
/home/naths/srcs/kwiver/vital/types/detected_object_set.cxx:93:24: error: no member named 'clone' in 'kwiver::vital::detected_object'
    new_obj->add( det->clone() );
                  ~~~  ^
/home/naths/srcs/kwiver/vital/types/detected_object_set.cxx:97:37: error: no member named 'clone' in 'kwiver::vital::attribute_set'
  new_obj->m_attrs = this->m_attrs->clone();
                     ~~~~~~~~~~~~~  ^

**Comment by skn123** [comment]
There are also issues with Eigen
/usr/local/include/eigen3/Eigen/src/Core/Matrix.h:296:22: error: no matching member function for call to '_init1'
      Base::template _init1<T>(x);
      ~~~~~~~~~~~~~~~^~~~~~~~~
/home/naths/srcs/kwiver/vital/types/camera.cxx:58:15: note: in instantiation of function template specialization 'Eigen::Matrix<double, 3, 3, 0, 3,
      3>::Matrix<kwiver::vital::rotation_<double> >' requested here
  matrix_3x3d R( this->rotation() );

I can get rid of this problem if I explicitly instantiate
matrix_3x3d t = this->rotation() and then pass it to R; 
I am using clang with -std=c++11 and -stdlib = libc++

**Comment by linus-sherrill** [comment]
We are still working on our support for clang, so I apologize for any difficulties.
Which version of clang are you using?

**Comment by skn123** [comment]
I am working with 4.0

**Comment by linus-sherrill** [comment]
The missing methods in the first set of errors are there. Seems odd that they are not being found. That code was recently added. Could there be some older libraries being used to link against, possibly in an install library?

**Comment by linus-sherrill** [comment]
I have not been able to reproduce that failure. Are you still having that problem?

**Comment by mleotta** [comment]
FYI, I just built against and updated version of Eigen and ran into this same error.  I’ve pushed a fix here:

https://github.com/Kitware/kwiver/pull/55 <https://github.com/Kitware/kwiver/pull/55>

**Comment by skn123** [comment]
The fix may not have been pushed as I am still getting errors. The previous error (first post) is also there.

**Comment by aclyde11** [comment]
```
    int array[9];
    for(int i = 0; i < 9; ++i) array[i] = i;
    Eigen::VectorXd v(array);
    std::cout << Eigen::Map<Eigen::MatrixXd>(v.data(), 3, 3) << std::endl;
```

gives /Users/austin/CLionProjects/CS28515Proj1/cmake-build-debug/eigen/src/eigen/Eigen/src/Core/Matrix.h:296:22: error: no matching member function for call to '_init1'
 as well.
