### PR TITLE
Introduce range helpers

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
"Ranges" is a feature space of upcoming C++ (i.e. C++17 and later) that simplifies common operations when working with sequences. Since it will be some time before KWIVER can rely on native support, this PR implements some of the more useful ones inside of KWIVER.

For now, the implemented range adapters are:
- `filter`: Apply a filter to a view, visit only those elements that pass the filter.
- `transform`: Apply a transformation to a view; visiting sees the element after the transformation has been applied.
- `sliding`: Visit elements according to a fixed-size sliding window. So, instead of visiting 0, 1, 2, ..., visit {0, 1, ..., N}, {1, 2, ...N+1}, ....

This also implements integer sequences (needed for `sliding`) and some other internal utilities needed to implement `filter` and `transform`.

Note that this is a private implementation of features that have been proposed for future C++, in order to avoid dependency creep. We could alternatively use [the proposal implementation](https://github.com/ericniebler/range-v3). We should plan eventually to migrate to standard C++, but this stuff won't be available for some time (probably not until we require C++20 or so).

Why is this stuff useful? Here is an example:

#### Before
```c++
  for ( auto const& sp : *input_track )
   {
    auto const osp = std::dynamic_pointer_cast< object_track_state >( sp );
    if ( !osp ) continue;

    auto const detection = osp->detection;
    if ( !detection ) continue;

    // do stuff with osp and/or detection
   }
```

#### After
```c++
  static auto has_detection =
    []( object_track_state* s ){ return s && s->detection; }
  for ( auto const& osp : *input_track | as_object_track
                                       | range::filter( has_detection ) )
  {
    // do stuff with osp
  }
```

(Note that `as_object_track` is also introduced in this PR. It looks like implementing and using `as_feature_track` would also be valuable, but my own immediate desire is for `as_object_track`.)

`sliding` is even more useful, as the alternative code is much less trivial.

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
I believe this is "ready" now if anyone wants to start reviewing the code. However, I still plan to add unit tests and a release note before removing the "WIP".

**Comment by mwoehlke-kitware** [comment]
> I believe this is "ready" now

Ahem. Modulo bugs... which is why I will be adding unit tests. (Already found and squashed some, can't promise there aren't others...)

**Comment by mwoehlke-kitware** [comment]
(I'm leaving for the day; someone remind me to write a release note if I forget :smile:...)

File: vital/range/filter.h [hunk 1]
```diff
@@ -0,0 +1,139 @@
...
+namespace vital {
+namespace range {
+
+// ----------------------------------------------------------------------------
+/// Filtering range adapter.
+/**
+ * This range adapter applies a filter to the elements of a range. When
+ * iterating over the range, only elements which pass the filter (that is, the
+ * filter functor returns \c true) will be seen.
+ */
```
Comment (linus-sherrill) [inline vital/range/filter.h]: It would be useful to have a small code example of how to use the range filter, even if the code is lifted from the tests.

File: vital/range/sliding.h [hunk 2]
```diff
@@ -0,0 +1,155 @@
...
+namespace range {
+
+// ----------------------------------------------------------------------------
+/// Sliding window range adapter.
+/**
+ * This range adapter provides a sliding view on a range. Given a \c Size, the
+ * first iteration will return that number of elements, in the same order as
+ * the input range. Each subsequent step will shift this window by one. If the
+ * input range has fewer than \c Size elements, the output range will be empty.
+ */
```
Comment (linus-sherrill) [inline vital/range/sliding.h]: It would be useful to have a small code example of how to use the sliding view adapter, even if the code is lifted from the tests.

File: vital/range/transform.h [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+
+namespace kwiver {
+namespace vital {
+namespace range {
+
+// ----------------------------------------------------------------------------
+/// Transforming range adapter.
+/**
+ * This range adapter applies a transformation to the elements of a range.
+ */
```
Comment (linus-sherrill) [inline vital/range/transform.h]: It would be useful to have a small code example of how to use the range transform adapter, even if the code is lifted from the tests.

**Comment by mwoehlke-kitware** [comment]
Okay, I added some examples and also hid a bunch of implementation details from Doxygen, so the resulting documentation should be more focused on what a user will actually use.

Also, do please ask about any bits you don't understand; in the process of doing the above, I noticed there was a crufty `operator|` overload left over in one of the tests from trying to make `c_array | sliding<N>` work. ([It can't](https://stackoverflow.com/questions/49639536).)

File: vital/types/object_track_set.h [hunk 4]
```diff
@@ -118,6 +126,9 @@ class VITAL_EXPORT object_track_set : public track_set
 /// Shared pointer for object_track_set type
 typedef std::shared_ptr< object_track_set > object_track_set_sptr;
 
+/// Helper to iterate over the states of a track as object track states
+inline auto as_object_track = range::transform( object_track_state::downcast );
```
Comment (dstoup) [inline vital/types/object_track_set.h]: This line of code is failing to build on my CentOS 7 machine, gcc 4.8.5-16

Comment (mwoehlke-kitware) [reply vital/types/object_track_set.h]: I'm not sure if I have a GCC 4.8 machine handy. Does this work?

```
inline decltype( range::transform( object_track_state::downcast ) )
as_object_track = range::transform( object_track_state::downcast );
```

(Is it the `inline` or the `auto` that GCC doesn't like?)

Fortunately I believe this can be worked around, at some aesthetic cost.

Comment (hughed2) [reply vital/types/object_track_set.h]: Here's the error I get on GCC 4.9

```
In file included from /var/jenkins_home/jobs/KwiverLinuxPR/workspace/sprokit/processes/kwiver_type_traits.h:48:0,
                 from /var/jenkins_home/jobs/KwiverLinuxPR/workspace/sprokit/processes/core/print_config_process.cxx:33:
/var/jenkins_home/jobs/KwiverLinuxPR/workspace/vital/types/object_track_set.h:130:13: error: ‘kwiver::vital::as_object_track’ declared as an ‘inline’ variable
 inline auto as_object_track = range::transform( object_track_state::downcast );
```

Comment (mwoehlke-kitware) [reply vital/types/object_track_set.h]: Yeah, apparently `-std=c++11` is insufficient for GCC to complain about this C++17 feature :stuck_out_tongue_closed_eyes:. 7b6f7b6328fe reworks this to use `constexpr` instead.

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
This branch is breaking Windows. See dashboard link above.

**Comment by mwoehlke-kitware** [comment]
Jenkins test this please

**Comment by mwoehlke-kitware** [comment]
Jenkins test this please
